#!/usr/bin/env bash
# This configures the domain zone so the subdomain www
#+ points to my load balancer, and then displays information about the subdomain

get_subdomain_spec () {
	dig $2.$1 | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom=$2 '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	record 0
}

get_subdomain_all () {
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomain[@]}"
	do
		dig $subdomain.$1 | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom="$subdomain" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	done
	return 0
}

# determine how many args are passed
if [ -z $2 ]
then
	get_subdomain_all "$1"
else
	get_subdomain_spec "$1" "$2"
fi
