#!/usr/bin/env bash
# This transfer a file from our client to a server
# scp must transfer the file to the user home directory ~/

file_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
file_name=$(basename "$BASH_SOURCE")
brown='\e[0;33m'
reset='\033[0m'
file="$1"
ip="$2"
user="$3"
key="$4"

if [ $# -ne 4 ]; then
	echo -e "Usage: ${brown}$file_name PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
else
	scp -i "$key" -o StrictHostKeyChecking=no "$file_path"/"$file" "$user"@"ip":/home/"$user"/
fi
