#!/usr/bin/env bash
# This transfer a file from our client to a server
# scp must transfer the file to the user home directory ~/

PATH_TO_FILE=$1
IP=$2
USERNAME="$3"
PATH_TO_KEY="$4"

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	sed -i '$ a \	StrictHostChecking no'	/etc/ssh/ssh_config
	scp -i "$PATH_TO_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
