#!/usr/bin/env bash
# This dubugs the problem with the ubuntu container's Nginx installation

sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
