#!/usr/bin/env bash
# This displays the numbers from 1 to 100
#+ Displays FizzBuzz when number is a multiple of 3 or 5
#+ Displays Fizz when the number is a multiple of 3
#+ Displays Buz when the number is a multiple of 5
#+ Otherwise display the number in a list format

i=1
while (( i<101 ))
do
	if (( i % 3 == 0 && i % 5 != 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 && i % 3 != 0 ))
	then
		echo "Buzz"
	elif (( i % 15 == 0 ))
	then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	((i++))
done
