#!/usr/bin/env bash
# Displays Best School 10 times and good luck on the 8th iteration
#+ and also displays bad luck on the 4th iteration

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 7 ]
	then
		echo "good luck"
	elif [ $i -eq 3 ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
	((i++))
done	
