#!/usr/bin/env bash
# Displays numbers from 1 to 20
#+ Displays "bad luck from China" on 4th loop iteration
#+ Displays "bad luck from Japan" on 8th loop iteration
#+ Displays "bad luck from Italy" on 17th loop iteration

i=1
while [ $i -lt 21 ]
do
	echo "$i"
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	((i++))
done
