#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes using only the while loop

i=0
while [ $i -lt 13 ]
do
	echo "Hour: $i"
	j=1
	while [ $j -lt 60 ]
	do
		echo "$j"
		((j++))
	done
	((i++))
done
