#!/usr/bin/env bash
# This configures an Ubuntu server
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1	localhost/127.0.0.2	localhost/' ~/hosts.new
sed -i '1s/^/8.8.8.8	facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
